In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

In [2]:
import math

In [3]:
import numpy as np

In [4]:
from numpy import arange
from timeit import Timer

Nelements = 10000
Ntimeits = 10000

x = arange(Nelements)
y = range(Nelements)

t_numpy = Timer("x.sum()", "from __main__ import x")
t_list = Timer("sum(y)", "from __main__ import y")
print("numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits,))
print("list:  %.3e" % (t_list.timeit(Ntimeits)/Ntimeits,))

numpy: 1.029e-05
list:  2.250e-04


# Pick out unique rows

In [ ]:
x = np.array([[1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0]])

In [ ]:
np.unique(x, axis=0)
np.unique(x)
np.unique(x, axis = 1)

In [ ]:
x.shape

In [ ]:
y = np.array([[1],[2],[3],[4],[5],[6]])

In [ ]:
y.shape

In [ ]:
z = np.dot(x, y)
z.shape

In [ ]:
np.sin(np.pi)

In [ ]:
np.sin(1.5707963267948966)

In [ ]:
np.arcsin(1)

In [ ]:
np.pi

In [ ]:
np.sin(0)
np.sin(2*np.pi)

<span style="font-family: Cosmic Sans MS; font-size:2em; color: #808000">
$$
P ( N ) = \left( \begin{array} { c } { n } \\ { N } \end{array} \right) p ^ { N } ( 1 - p ) ^ { n - N }
$$
    
binomial(n, p, size=None)

In [ ]:
np.random.binomial(2,0.3)

In [ ]:
np.random.binomial(2,0.1, size=300)

In [ ]:
np.random.chisquare()

In [ ]:
math.log(10)

In [ ]:
def Pkernel(x):
    """Kernel function from Biteau & Williams (2015), Eq. (7)"""

    m = (x < 0.) & (x >= 1.)
    x[x < 0.] = np.zeros(np.sum(x < 0.))
    x[x >= 1.] = np.zeros(np.sum(x >= 1.))
    x = np.sqrt(x)

    result = np.log(2.) * np.log(2.)  - np.pi *np.pi / 6. \
	    + 2. * spence(0.5 + 0.5 * x) - (x + x*x*x) / (1. - x*x) \
	    + (np.log(1. + x) - 2. * np.log(2.)) * np.log(1. - x) \
	    + 0.5 * (np.log(1. - x) * np.log(1. - x) - np.log(1. + x) * np.log(1. + x)) \
	    + 0.5 * (1. + x*x*x*x) / (1. - x*x) * (np.log(1. + x) - np.log(1. - x))
    result[x <= 0.] = np.zeros(np.sum(x <= 0.))
    result[x >= 1.] = np.zeros(np.sum(x >= 1.))
    return result

In [ ]:
np.log10(1e4)

In [ ]:
3e4

In [ ]:
np.zeros([3,4], dtype='int')
np.ones([3,4], dtype='int') 
np.linspace(-7, 2, 10, 0) 

In [ ]:
ar2d = np.array([[1, 2, 3], [11, 12, 13], [10, 20, 40]], dtype='uint8', order='C')

In [ ]:
ar2df = np.array([[1, 2, 3], [11, 12, 13], [10, 20, 40]], dtype='uint8', order='F')

 # Numpy array
 Numpy arrays have a fixed size at creation, unlike python lists (which can grow dynamically).

# Numpy Matrix

In [22]:
A = np.matrix([[1,3,7],[2,8,3],[7,8,1]])
A

matrix([[1, 3, 7],
        [2, 8, 3],
        [7, 8, 1]])

In [23]:
# Transpose matrix of A
A_T = A.transpose()
A_T

matrix([[1, 2, 7],
        [3, 8, 8],
        [7, 3, 1]])

In [24]:
np.multiply(A,A_T)

matrix([[ 1,  6, 49],
        [ 6, 64, 24],
        [49, 24,  1]])

In [25]:
# Inverse of A
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 0.06694561, -0.22175732,  0.19665272],
        [-0.07949791,  0.20083682, -0.0460251 ],
        [ 0.16736402, -0.05439331, -0.0083682 ]])

In [26]:
np.multiply(A,A_inv)

matrix([[ 0.06694561, -0.66527197,  1.37656904],
        [-0.15899582,  1.60669456, -0.13807531],
        [ 1.17154812, -0.43514644, -0.0083682 ]])

In [27]:
np.dot(A, A_inv)

matrix([[ 1.00000000e+00,  2.77555756e-17, -8.67361738e-18],
        [-2.77555756e-17,  1.00000000e+00, -4.33680869e-17],
        [ 8.32667268e-17,  8.32667268e-17,  1.00000000e+00]])

In [28]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes
